### ISSUE TITLE
crack database license

### ISSUE THREAD

**Issue by omoghadasi** [dinar-it/odoo_16_enter#1]
Hello
Thanks for sharing this repository
I installed the modules of this developer on my Odoo, but the problem I have is related to the expiration date of my database. Can you help me change the expiration date of the database?

**Comment by dinar-it** [comment]
Hello
you are welcome
this repo for only enterprise addones not cracked
so i installed it and bought license from odoo

thanks

**Comment by dinar-it** [comment]
for sure this is odoo 16.0 version and it's not updated
if you want last version you must download from odoo it self
they required subscription to download enterprise edition
thanks

**Comment by omoghadasi** [comment]
Thank you very much for your advice
